# .pre-commit-config.yaml
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.257  # Use the latest version or specify a specific version
    hooks:
      - id: ruff
        args: ["--fix", "--select", "ALL", "--ignore", "E501"]  # Adjust arguments as needed

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971  # Use the latest version or specify a specific version
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]  # Adjust arguments as needed

  - repo: https://github.com/psf/black
    rev: 23.3.0  # Use the latest version or specify a specific version
    hooks:
      - id: black
        args: ["--line-length", "88"]  # Adjust arguments as needed
